---
- name: Install firewalld
  package:
    name: firewalld
    state: present

- name: Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: FW Rules - Master
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items: '{{ k8s_master_ports }}'
  when: "'master' in ansible_hostname"

- name: FW Rules - Worker
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items: '{{ k8s_worker_ports }}'
  when: "'worker' in ansible_hostname"

# Activate transparent masquerading
# to allow PODs communication via VXLAN
- name: Activate transparent masquerading
  firewalld:
    masquerade: yes
    state: enabled
    permanent: true

- name: Reload firewalld service
  systemd:
    name: firewalld
    state: reloaded

# Alternative option
#- name: Reload firewalld
#  shell: firewall-cmd --reload