---
- name: Add docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

# Check for current supported version:
# https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml
# At the moment v 20.10 is listed
- name: Install supported version of Docker
  package:
    name: docker-ce-20.10.7-3.el8
    state: present

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/docker
    - /etc/systemd/system/docker.service.d

- name: Start and enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes